language: node_js
node_js:
  - 6

os:
  - linux

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
